name: Gitea Actions
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  EC7xx:
    runs-on: ubuntu-latest
    strategy:    
      matrix:
        csdk_project: ["example", "example_adc", "example_fskv", "example_gpio", "example_uart", "example_rndis", "example_rtc", "example_luatos_socket", "example_luatos_mqtt"]
        csdk_chip: ["ec718p", "ec718s", "ec716s"]
    steps:
      - name: 克隆 LuatOS 代码库
        run:  git clone --depth=1 http://192.168.1.231:13000/openLuat/LuatOS.git
      - name: 克隆 ec7xx-csdk 代码库
        run:  git clone --depth=1 http://192.168.1.231:13000/openLuat/luatos-soc-2023.git
      - name: 安装 xmake
        run:  curl -fsSL https://xmake.io/shget.text | bash
      - name: 初始化工具链
        run: |
          mkdir tools
          cd tools
          wget http://cdndownload.openluat.com/xmake/toolchains/gcc-arm/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          tar xf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          ls -l
          cd ..
          sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
          sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
          dpkg --add-architecture i386 && apt update
          apt-get install -y lib32z1 binutils:i386 libc6:i386 libgcc1:i386 libstdc++5:i386 libstdc++6:i386 p7zip-full
      - name: 构建指定项目
        run: |
          export GCC_PATH=`pwd`/tools/gcc-arm-none-eabi-10-2020-q4-major
          export XMAKE_MAIN_REPO=https://gitee.com/tboox/xmake-repo.git
          source ~/.xmake/profile
          cd luatos-soc-2023
          xmake -y --root
          rm -fr build
        env:
          PROJECT_NAME: ${{ matrix.csdk_project }}
          CHIP_TARGET: ${{ matrix.csdk_chip }}
