#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.77.207, Sat Mar 23 22:11:17 2024

#define DB_VERSION_UNIQ_ID "0x7dfc00f7"

#endif //_DB_VERSION_H
