#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.77.207, Tue Feb 20 20:04:11 2024

#define DB_VERSION_UNIQ_ID "0x71e21bc2"

#endif //_DB_VERSION_H
